idf_component_register(
    SRCS
        "app_main.c"
        "usb_dualsense_descriptor.c"
        "dualsense_report.c"
        "dualsense_report_mapper.c"
        "pro2_input_backend.c"
        "pro2_rumble_backend.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp_tinyusb
        pro2_bridge_reuse
        nvs_flash
        esp_timer
)
