param(
    [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$SourceRoot = "",
    [string]$OutputPath = ""
)

$ErrorActionPreference = "Stop"
$ProjectRoot = (Resolve-Path $ProjectRoot).Path

if ([string]::IsNullOrWhiteSpace($SourceRoot)) {
    $SourceRoot = Join-Path $ProjectRoot "research\upstream\DS5Dongle"
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $ProjectRoot "docs\generated\v5_5_ds5dongle_symbol_scan.md"
}

function Write-AnalyzeLine {
    param([string]$Key, [object]$Value)
    if ($Value -is [bool]) { $Value = $Value.ToString().ToLowerInvariant() }
    if ($null -eq $Value -or $Value -eq "") { $Value = "not_found" }
    Write-Output "[V5_5_DS5_ANALYZE] $Key=$Value"
}

function Get-RepoRelativePath {
    param([string]$BasePath, [string]$TargetPath)
    $baseFull = [IO.Path]::GetFullPath($BasePath).TrimEnd("\", "/") + [IO.Path]::DirectorySeparatorChar
    $targetFull = [IO.Path]::GetFullPath($TargetPath)
    $baseUri = New-Object Uri($baseFull)
    $targetUri = New-Object Uri($targetFull)
    return [Uri]::UnescapeDataString($baseUri.MakeRelativeUri($targetUri).ToString())
}

if (!(Test-Path (Join-Path $SourceRoot ".git"))) {
    Write-AnalyzeLine "source" $SourceRoot
    Write-AnalyzeLine "blocked" $true
    Write-AnalyzeLine "reason" "DS5Dongle source is missing; run .\tools\fetch_v5_5_ds5dongle.ps1"
    exit 0
}

$requestedFiles = @(
    "src/usb_descriptors.cpp",
    "src/usb.cpp",
    "src/audio.cpp",
    "src/bt.cpp",
    "src/main.cpp",
    "src/state_mgr.cpp",
    "src/cmd.cpp",
    "src/config.cpp",
    "src/tusb_config.h",
    "CMakeLists.txt",
    "LICENSE"
)

$categories = @(
    @{
        Name = "Descriptors and identity"
        Pattern = "idVendor|idProduct|DualSense|TUD_CONFIG_DESCRIPTOR|TUD_AUDIO|TUD_HID|desc_device|report_desc"
    },
    @{
        Name = "Endpoints and interfaces"
        Pattern = "EPNUM|EP_NUM|ENDPOINT|ITF_NUM|INTERFACE|TUD_AUDIO_SPEAKER_STEREO|TUD_HID_INOUT_DESCRIPTOR"
    },
    @{
        Name = "Report builders and feature reports"
        Pattern = "tud_hid_report|get_feature_data|set_feature_data|report_id|REPORT_ID|interrupt_in_data"
    },
    @{
        Name = "Output callbacks and state"
        Pattern = "tud_hid_set_report_cb|state_update|rumble|trigger|light|mute|player"
    },
    @{
        Name = "Audio callbacks and format"
        Pattern = "tud_audio|SAMPLE_RATE|INPUT_CHANNELS|OUTPUT_CHANNELS|SAMPLE_SIZE|N_CHANNELS|BYTES_PER_SAMPLE"
    },
    @{
        Name = "Haptic packet path"
        Pattern = "haptic|haptics|resample|pkt\[|REPORT_SIZE|REPORT_ID|audio_buf"
    },
    @{
        Name = "Bluetooth backend coupling"
        Pattern = "bt_write|bt_init|L2CAP|get_feature_data|set_feature_data|CYW43|pico_btstack"
    }
)

$commit = (& git -C $SourceRoot rev-parse HEAD 2>$null).Trim()
$branch = (& git -C $SourceRoot branch --show-current 2>$null).Trim()
$licenseName = if (Test-Path (Join-Path $SourceRoot "LICENSE")) { "LICENSE (MIT)" } else { "not_found" }
$relativeSource = Get-RepoRelativePath -BasePath $ProjectRoot -TargetPath $SourceRoot
$relativeOutput = Get-RepoRelativePath -BasePath $ProjectRoot -TargetPath $OutputPath

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# V5.5 DS5Dongle Symbol Scan")
$lines.Add("")
$lines.Add('Generated by `.\tools\analyze_v5_5_ds5dongle.ps1`. The upstream checkout is ignored and is not committed.')
$lines.Add("")
$lines.Add('```text')
$lines.Add("repository=https://github.com/awalol/DS5Dongle")
$lines.Add("source=$relativeSource")
$lines.Add("commit=$commit")
$lines.Add("branch=$branch")
$lines.Add("license=$licenseName")
$lines.Add('```')
$lines.Add("")
$lines.Add("## Files")
$lines.Add("")
$lines.Add("| File | Present |")
$lines.Add("| --- | --- |")
foreach ($relativeFile in $requestedFiles) {
    $present = Test-Path (Join-Path $SourceRoot $relativeFile)
    $lines.Add(('| `{0}` | {1} |' -f $relativeFile, $present.ToString().ToLowerInvariant()))
}

$lines.Add("")
$lines.Add("## Machine Summary")
$lines.Add("")
$lines.Add('- USB identity is implemented in `src/usb_descriptors.cpp` with Sony VID `0x054C` and runtime DS5/Edge PID selection.')
$lines.Add("- The USB shape combines HID with bidirectional audio streaming; optional CDC is a build option.")
$lines.Add("- PC audio enters through TinyUSB audio callbacks. Four 48 kHz, 16-bit OUT channels are split into speaker L/R and haptic L/R.")
$lines.Add('- Haptic channels are resampled and packed into Bluetooth output report `0x36` for a real DualSense.')
$lines.Add('- USB HID OUT report `0x02` is decoded by `state_update` and then forwarded through `bt_write`.')
$lines.Add('- Input report `0x01` and several feature reports are sourced from the real DualSense Bluetooth backend.')
$lines.Add("- The V5.5 port should retain the PC-facing USB contract while replacing the real-DualSense backend with Pro2 BLE input and raw02 output backends.")

foreach ($category in $categories) {
    $lines.Add("")
    $lines.Add("## $($category.Name)")
    $lines.Add("")
    $matchCount = 0

    foreach ($relativeFile in $requestedFiles) {
        $fullPath = Join-Path $SourceRoot $relativeFile
        if (!(Test-Path $fullPath) -or $matchCount -ge 36) {
            continue
        }

        $matches = @(Select-String -LiteralPath $fullPath -Pattern $category.Pattern -CaseSensitive:$false |
            Select-Object -First ([Math]::Max(0, 36 - $matchCount)))
        foreach ($match in $matches) {
            $snippet = $match.Line.Trim().Replace('`', "'")
            if ($snippet.Length -gt 180) {
                $snippet = $snippet.Substring(0, 177) + "..."
            }
            $lines.Add(('- `{0}:{1}`: `{2}`' -f $relativeFile, $match.LineNumber, $snippet))
            $matchCount++
        }
    }

    if ($matchCount -eq 0) {
        $lines.Add("- No matching symbols found.")
    }
}

$lines.Add("")
$lines.Add("## Port Boundary")
$lines.Add("")
$lines.Add('```text')
$lines.Add("PcFacingDualSenseDevice")
$lines.Add("  input_report_builder")
$lines.Add("  output_report_receiver")
$lines.Add("  audio_haptic_receiver")
$lines.Add("")
$lines.Add("ControllerBackend")
$lines.Add("  Ds5BtBackend             # upstream reference/validation only")
$lines.Add("  Pro2BleInputBackend      # real product input")
$lines.Add("  Pro2Raw02Backend         # real product haptic output")
$lines.Add('```')

New-Item -ItemType Directory -Force (Split-Path -Parent $OutputPath) | Out-Null
$lines | Set-Content -LiteralPath $OutputPath -Encoding utf8

Write-AnalyzeLine "source" $relativeSource
Write-AnalyzeLine "commit" $commit
Write-AnalyzeLine "branch" $branch
Write-AnalyzeLine "output" $relativeOutput
Write-AnalyzeLine "result" "passed"
